[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  AUTH_SECRET = "f3f1e9c2b4a5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1"
  AUTH_URL = "https://soft-taller.netlify.app"
  NEXTAUTH_URL = "https://soft-taller.netlify.app"
  AUTH_TRUST_HOST = "true"
  DATABASE_URL = "postgresql://neondb_owner:npg_v82NJhIezyYZ@ep-divine-darkness-acaj5nwm-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&pgbouncer=true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
